### ISSUE TITLE
Network connectivity is not stable

### ISSUE THREAD

**Issue by jeffswt** [GangZhuo/BaiduPCS#175]
![image](https://cloud.githubusercontent.com/assets/18145331/25469228/9cdfd204-2b4d-11e7-8d4a-becd2c6fa8c9.png)

Typically all the 20 threads read data at one blow and then stops for a couple of seconds.

This might be an implementation issue caused by the server. However, you could add a "reset timeout" for the command line utility so that connections would be resetted every couple of seconds, making the speed stable at least.

--------

I personally had to write a Python tweak for this issue, namely the one below:

```Python
import os
import sys
import time
import threading

src = sys.argv[1]
tgt = sys.argv[2]

while True:
    if os.path.exists(tgt):
        break
    def foo():
        time.sleep(9)
        os.system('taskkill /f /im pcs.exe')
    threading.Thread(target=foo).start()
    os.system('pcs download "%s" "%s"' % (src, tgt))
    pass
```

So see if you could implement this in the CLI.

**Comment by GangZhuo** [comment]
Timeout caused by server limitations. Reconnect frequently will aggravate
the issue.

Geoffrey, Tang <notifications@github.com>于2017年4月27日周四 下午1:31写道：

**Comment by jeffswt** [comment]
1. This does not happen from time to time. It happens since the first connection.
2. I have a configuration of 20 threads at concurrency.
3. It seems that frequent reconnections can resolve the problem, such like a distributed phase clock (I can explain this further if you would like to know).
4. Maybe I need to emphasize that it's not a timeout. Under normal situations, the data transfer graph is likely to be similar to this one, only that the gap is way longer. They **do not timeout**, just don't transfer data very regularly.

---

I have a probable solution to this.

*   If one thread stops transferring data, stop it and reconnect after a grace period.
*   Start threads one by one with a delay, which can prevent outbursts and mass silences.

Sincerely hope that this would not be a lot of work.

**Comment by bbscool** [comment]
I've worked out a quick fix. I'm sure that it is not a perfect solution so instead of firing a pulling request, I'll show you what I did.

According to @jeffswt suggestion:

_a.If one thread stops transferring data, terminate it and reconnect after a grace period of 8 to 9 seconds._
  **-> Can be achieved by setting libcurl's timeout value.**

in pcs_http_create @ pcs_http.c, search 
`http->timeout = 0`
if you change this value to some other like 5 or so, that means libcurl will terminate the connection in 5 seconds since download begins.

There's a side-effect of doing that modification. Error message says the connection has been terminated due to timeout issue will appear every 5 seconds. So we have to mute this message.

in pcs_http_perform @ pcs_http.c, search 
`if (!http->strerror) http->strerror`
add following code below:
`  if (res == CURLE_OPERATION_TIMEDOUT) http->strerror = "TIMEOUT_MUTE";`

in pcs_download_normal @ pcs.c search 
`errmsg = pcs_http_strerror(pcs->http);`
, change the code after this line into this:

> 
> 	if (errmsg && strcmp(errmsg, "TIMEOUT_MUTE") != 0) {  // <- "timeout error" will not be set.
> 		if (errmsg)
> 			pcs_set_serrmsg(handle, errmsg);
> 		else
> 			pcs_set_errmsg(handle, "Can't download the file: %s", pcs_http_strerror(pcs->http));
> 	}
> 
> 

in download_thread @ shell.c, search 
`Download slice failed, retry delay 10 second,`
, change the code into this:

> if (pcs_strerror(pcs)) {  // <-- if error message has been set, show that.
> #ifdef _WIN32
> printf("Download slice failed, retry delay 10 second, tid: %x. message: %s\n", GetCurrentThreadId(), pcs_strerror(pcs));
> #else
> printf("Download slice failed, retry delay 10 second, tid: %p. message: %s\n", pthread_self(), pcs_strerror(pcs));
> #endif
> sleep(1); /1秒后重试/ //
> }
> 

_b.Start threads one by one with a delay, which can prevent outbursts or mass silences._
  **-> A few lines of code can do the trick.**

in shell.c, search 
`  for (i = 0; i < thread_count; i++) {`
add some caviar like the following:

>  int pause_thread_count = 0;
>   for (i = 0; i < thread_count; i++) {
> #ifdef _WIN32
> start_download_thread(&ds, handles + i);
> #else
> start_download_thread(&ds, NULL);
> #endif
> if (++pause_thread_count >= thread_count / 5) {
> pause_thread_count = 0;
> sleep(1);
> }

}


I've tested the code and result turns out be good.

download using original program:
![pcs](https://cloud.githubusercontent.com/assets/2800994/25980966/271f19aa-370d-11e7-9654-9cd67fca88fa.PNG)

after do the patch:
![pcs1](https://cloud.githubusercontent.com/assets/2800994/25980978/41595ad8-370d-11e7-89f3-18ce5a91f485.PNG)

**Comment by jeffswt** [comment]
@bbscool I'm pretty much sure that this works way better than my Python workaround.

For the second fix you mode, it works pretty well for that certain condition. And I think you should make a pull request for that feature, as this could really improve thread performance.

However, as far as I am concerned, the problem that I encountered does not apply to all networks. In certain network conditions, this does not happen. **So we might consider not making this mandatory.** Maybe a configuration could work, or a detection should do the job.

Anyway, it's a nice patch you've made. Thumbs up for it - And I really hope you could make it a pull request.

**Comment by GangZhuo** [comment]
@bbscool awesome, please make a pull request.

**Comment by mayuuko** [comment]
I believe that a lot of people dont understand your work here but countering same problem.
If above work was effective to improve the network connectivity to be more stable,
would be somehow a update on this project later for helping us to use continuously?
Poor English and hope you understand. Thank you!

**Comment by jeffswt** [comment]
@bbscool This solution **SHOULD NOT BE USED IN PRODUCTION**.

I have been using this for a while now, and currently I am running into loads of problems.

Files are not downloaded correctly, and due to several reconstructions at the server-end (i guess so) all files downloaded hence have CRC failures, particularly those in packaged format.

Consider refactoring the project.
